### ISSUE TITLE
Stuck at 95% emitting

### ISSUE THREAD

**Issue by iqbalhs** [developeruz/yii-vue-app#1]
### What steps will reproduce the problem?
Trying to Install the template via composer.
### What's expected?
Template to be installed correctly.
### What do you get instead?
Stuck at 95% emitting on `yarn dev`

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.15.1
| PHP version      | 7.1.15
| Operating system | Windows 10

**Comment by iqbalhs** [comment]
Just find out this might be related to [this issue](https://github.com/JeffreyWay/laravel-mix/issues/1126).

I added the following on my `webpack.min.js`
```
mix.setPublicPath('web/');
```

Now it works like a charm.

**Comment by developeruz** [comment]
Thank you a lot! I've added this line to the project's webpack.min.js.
