### ISSUE TITLE
Error: Can't resolve 'babel-loader' while composer create-project

### ISSUE THREAD

**Issue by faustoFF** [developeruz/yii-vue-app#2]
### What steps will reproduce the problem?

php composer.phar create-project --prefer-dist --stability=dev developeruz/yii-vue-app basic

### What's expected?

composer install completed

### What do you get instead?

Error while install:

```
> yarn install
...
> yarn dev
yarn run v1.6.0
$ cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
 ERROR  Failed to compile with 1 errors00:00:27

This dependency was not found:

* APP_PATH\app\app.js in multi ./app/app.js

To install it, you can run: npm install --save APP_PATH\app\app.js
  Asset     Size  Chunks             Chunk Names
/app.js  2.65 kB       0  [emitted]  /app

ERROR in multi ./app/app.js
Module not found: Error: Can't resolve 'babel-loader' in 'APP_PATH'
 @ multi ./app/app.js
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
Script yarn dev handling the post-create-project-cmd event returned with error code 1
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |2.0.15.1
| PHP version      |7.0
| Operating system |Linux/Windows

**Comment by faustoFF** [comment]
This can be fixed by adding `"babel-loader": "^7.1.4"` in to `devDependencies` section of `package.json` file in root of project.

**Comment by developeruz** [comment]
`babel-loader` is a dependency of `laravel-mix@2.1`. There is no reason to add it manually to package.json. Try to run `yarn install` before `yarn dev`

**Comment by faustoFF** [comment]
Exactly `yarn install` was failed with error described on this issue.
